### REGISTER USER

POST http://localhost:5000/api/auth/register
content-type: application/json

{
    "name":"Ansh Rusia",
    "email":"ansh@ams.com",
    "role":"user",
    "password":"ansh1212"
}

### LOGIN USER

POST http://localhost:5000/api/auth/login
content-type: application/json

{
    "email":"varun@ams.com",
    "password":"varun1212"
}

### GET ALL USER

GET http://localhost:5000/api/auth/users

### GET SINGLE USER

GET http://localhost:5000/api/auth/users/636a5c4f003707ac95d37ff6  

### UPDATE USER PRIVILEGE

PUT http://localhost:5000/api/auth/users/636a60aca3b745ce301f7a2f  
Content-Type: application/json

{
    "role":"user"
}

### DELETE USER

DELETE  http://localhost:5000/api/auth/users/636a5efe1903304e6747da72  