### REGISTER USER

POST http://localhost:5000/api/auth/register
content-type: application/json

{
    "name":"Rajesh Tiwari",
    "dob": "12-12-2001",
    "department": "IMT-2020",
    "address": "Rajul Nagar",
    "phoneNumber": "1212121212",
    "rollNumber": "2020IMT-112",
    "email":"rajesh@ams.com",
    "role":"user",
    "password":"varun1212"
}

### LOGIN USER

POST http://localhost:5000/api/auth/login
content-type: application/json

{
    "email":"varun@ams.com",
    "password":"varun1212"
}

### GET ALL USER

GET http://localhost:5000/api/auth/users

### GET SINGLE USER

GET http://localhost:5000/api/auth/users/636ea492d70ea42449d50993  

### UPDATE USER PROFILE

PUT http://localhost:5000/api/auth/users/636e7eb7b2835c5590b31a46  
Content-Type: application/json

{
    "role": "user"
}

### DELETE USER

DELETE  http://localhost:5000/api/auth/users/636ea492d70ea42449d50993  