### REGISTER USER

POST http://localhost:5000/api/auth/register
content-type: application/json

{
    "name":"Varun Tiwari",
    "dob": "12-12-2001",
    "department": "IMT-2020",
    "address": "Rajul Nagar",
    "phoneNumber": "1212121212",
    "rollNumber": "2020IMT-112",
    "email":"varun@ams.com",
    "role":"admin",
    "password":"varun1212"
}

### LOGIN USER

POST http://localhost:5000/api/auth/login
content-type: application/json

{
    "email":"varun@ams.com",
    "password":"varun1212"
}

### GET ALL USER

GET http://localhost:5000/api/auth/users

### GET SINGLE USER

GET http://localhost:5000/api/auth/users/636e78ee53722de0c6a8594d  

### UPDATE USER PRIVILEGE

PUT http://localhost:5000/api/auth/users/636e78ee53722de0c6a8594d  
Content-Type: application/json

{
    "dob": "11/09/2001"
}

### DELETE USER

DELETE  http://localhost:5000/api/auth/users/636e6006b115e8c20661e49b  